# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://www.antoniomallia.it
baseurl: /
title: Antonio Mallia's personal blog
author: Antonio Mallia
description: Personal blog and resume
avatar: profile.jpg
email: me@antoniomallia.it
github: amallia # username
twitter: antonio_mallia
linkedin: antoniomallia
skype: antonio.mallia
telegram: antoniomallia
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: amallia
google_analytics: UA-105098818-1

# needed for travis-ci build
exclude: [vendor]
